title: VUEngine Studio
permalink: pretty
nav:
  pages:
    Home: "/"
    Docs: "/documentation/"
    Games: "/games/"
    Download: "/downloads/"
    About: "/about/"
plugins:
  - "jekyll-github-metadata"
repository: VUEngine/VUEngine-Studio
