title: VUEngine Studio
permalink: pretty
nav:
  pages:
    About: "/about/"
    Documentation: "/documentation/"
    Games: "/games/"
    # Download: "https://github.com/VUEngine/VUEngine-Studio/releases"
plugins:
  - "jekyll-github-metadata"
repository: VUEngine/VUEngine-Studio
