title: VUEngine Studio
permalink: pretty
nav:
  pages:
    Home: "/"
    Documentation: "/documentation/"
    #Games: "/games/"
plugins:
  - "jekyll-github-metadata"
repository: VUEngine/VUEngine-Studio
