title: VUEngine Studio
permalink: pretty
nav:
  pages:
    Download: "/"
    Documentation: "/documentation/"
    Games: "/games/"
plugins:
  - "jekyll-github-metadata"
repository: VUEngine/VUEngine-Studio
